[package]
name = "password-encryptor"
version = "0.0.1"
edition = "2021"
description = "A helper for encrypting and validating password"
license = "MIT"


[dependencies]
base64-url = "2.0.2"
hmac = "0.12.1"
sha2 = "0.10.8"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
